# Fake DNS API: ServiceAccount
#
# ServiceAccount for the fake DNS API pod. Required for OpenShift security
# context constraints when running with elevated privileges for port 53.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fake-dns-api
  namespace: ${FAKEDNS_NAMESPACE}

