apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-dns
  namespace: ${ACMEDNS_NAMESPACE}
  labels:
    app: acme-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-dns
  template:
    metadata:
      labels:
        app: acme-dns
    spec:
      containers:
      - name: acme-dns
        image: joohoi/acme-dns:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: api
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/acme-dns
          readOnly: true
        - name: data
          mountPath: /var/lib/acme-dns
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: acme-dns-config
      - name: data
        emptyDir: {}

